import { Metadata } from "next";
import { Plus_Jakarta_Sans, Bungee, Black_Ops_One, Great_Vibes } from "next/font/google";
import NavBar from "./components/NavBar";
import Footer from "./components/Footer";
import ThemeProvider from "./components/ThemeProvider";
import Background3D from "./components/Background3D";
import "./globals.css";

const plusJakartaSans = Plus_Jakarta_Sans({
  subsets: ["latin"],
  variable: "--font-body",
  display: "swap",
});

const bungeeHeading = Bungee({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-heading",
  display: "swap",
});

const blackOpsOne = Black_Ops_One({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-black-ops",
  display: "swap",
});

const greatVibes = Great_Vibes({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-great-vibes",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Muhammad Salman",
  description: "Generated by Muhammad Salman",
  icons: {
    icon: "./avatar.svg",
  },
  keywords: [
    "MSalman3428",
    "github",
    "muhammad salman github",
    "Muhammad Salman",
    "Web Developer",
    "Frontend Developer",
    "Next.js Developer",
    "React Developer",
    "JavaScript",
    "Portfolio",
    "Web Design",
    "UI/UX",
    "SEO Optimized Website"
  ],
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
      <html
          lang="en"
          className={`${plusJakartaSans.variable} ${bungeeHeading.variable} ${blackOpsOne.variable} ${greatVibes.variable}`}
          suppressHydrationWarning
      >
      <body className="antialiased min-h-screen relative overflow-x-hidden">
      <ThemeProvider>
        {/* Background mounted globally to remain active on all routes */}
        <Background3D />
        <div className="relative z-10 flex flex-col min-h-screen">
          <NavBar />
          <main className="flex-grow w-full max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
            {children}
          </main>
          <Footer />
        </div>
      </ThemeProvider>
      </body>
      </html>
  );
}