import { Metadata } from "next";
import NavBar from "./components/NavBar";
import Footer from "./components/Footer";
import "./globals.css";

export const metadata: Metadata = {
  title: "Muhammad Salman",
  description: "Generated by Muhammad Salman",
  icons: {
    icon: "/favicondark.ico",
  },
  keywords: [
    "MSalman3428",
    "github",
    "muhammad salman github",
    "Muhammad Salman",
    "Web Developer",
    "Frontend Developer",
    "Next.js Developer",
    "React Developer",
    "JavaScript",
    "Portfolio",
    "Web Design",
    "UI/UX",
    "SEO Optimized Website"
  ],
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className="antialiased">
        <NavBar />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
